image: nikolaik/python-nodejs:python3.6-nodejs12-stretch

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - pip install -r requirements.txt
    - python -m unittest

production:
  stage: deploy
  before_script:
    - npm config set prefix /usr/local
    - npm install -g serverless
    - npm install --save serverless-python-requirements
  script:
    - serverless deploy --stage production --verbose
  environment: production
