service: amr-aws

app: amr-aws-app
org: madusha2018828

frameworkVersion: "2"

package:
  individually: true
  exclude:
    - node_modules/**
    - yolo-model/**

plugins:
  - serverless-python-requirements
  # - serverless-dynamodb-local
  # - serverless-offline

custom:
  pythonRequirements:
    dockerizePip: non-linux
  dynamodb:
    start:
      migrate: true
    stages:
      - production
      - dev

provider:
  name: aws
  runtime: python3.6
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:923250232734:table/devicesTable"
  apiGateway:
    binaryMediaTypes:
      - "*/*"

functions:
  test:
    handler: lambdas/handler.hello
    events:
      - http:
          path: test
          method: get
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: ApiGatewayAuthorizer

  update_push_token:
    handler: lambdas/fcm/push_token_handler.update_token
    events:
      - http:
          path: fcm/updatePushToken
          method: post

  send_push_notification:
    handler: lambdas/fcm/push_message_handler.send_notification
    module: lambdas/fcm
    events:
      - http:
          path: fcm/sendPushMessage
          method: post

  read_digits:
    handler: lambdas/meter_reader/handler.read_digits
    module: lambdas/meter_reader
    package:
      include:
        - yolo-model/**
    events:
      - http:
          path: meter_reader/read_digits
          method: post

resources:
  Resources:
    ApiGatewayAuthorizer:
      DependsOn:
        - ApiGatewayRestApi
      Type: AWS::ApiGateway::Authorizer
      Properties:
        Name: cognito-authorizer
        IdentitySource: method.request.header.Authorization
        RestApiId:
          Ref: ApiGatewayRestApi
        Type: COGNITO_USER_POOLS
        ProviderARNs:
          # arn should get from the generated user pool from frontend
          - arn:aws:cognito-idp:us-east-1:923250232734:userpool/us-east-1_X8rQ1Si4k
    DevicesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: devicesTable
        AttributeDefinitions:
          - AttributeName: deviceId
            AttributeType: S
        KeySchema:
          - AttributeName: deviceId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
